name: Publish app to beta on Android PlayStore
# on: workflow_dispatch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Cloning project repository
      - uses: actions/checkout@v3

      # Setup Flutter
      - name: Retrieve cached Flutter installation
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: |
            ~/flutter
            ~/.pub-cache
          key: ${{ runner.os }}-${{ hashFiles('**/.fvm/fvm_config.json') }}

      - name: Add Flutter to path
        if: steps.cache-flutter.outputs.cache-hit == 'true'
        run: |
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Clone and install Flutter repository with master channel
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: britannio/action-install-flutter@v1.1
        with:
          version: 1.22.6

      - name: Retrieve cached dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Download project dependencias
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/$KEYSTORE_STORE_FILE
          echo "storeFile=$KEYSTORE_STORE_FILE" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          echo "$PLAY_STORE_CONFIG_JSON" > ../fastlane-user.json
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_STORE_FILE: ${{ secrets.KEYSTORE_STORE_FILE }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      - name: Building Appbundle
        run: flutter build appbundle
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Deploy Appbundle to PlayStore on Beta
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: deploy_beta
          subdirectory: android
